### ISSUE TITLE
Introduce version numbers

### ISSUE THREAD

**Issue by SimonEbner** [KayEss/json-schema#1]
It would be nice if you could push tags in order to check out a well defined version, rather than commits

**Comment by KayEss** [comment]
It should have been tagged a few weeks ago when we did the Fost release. Normally I wouldn't put any other sort of version number on the library.

What will happen is that master will get tagged every quarter. Does this satisfy what you need from the version numbers?

**Comment by SimonEbner** [comment]
Sure, thank you.
