### ISSUE TITLE
A Compilation Problem

### ISSUE THREAD

**Issue by walterzhaoJR** [KayEss/json-schema#5]
code branch:master

I modified cmake file：
target_compile_options(f5-json-schema INTERFACE -std=c++17) to target_compile_options(f5-json-schema INTERFACE -std=c++11)
and i find the problem:
fatal error: fost/json: No such file or directory

**Comment by KayEss** [comment]
Hi, thanks for trying it out!

Unfortunately the JSON library that it uses is here <https://github.com/KayEss/fost-base>, and that in turn requires a few other libraries :( We are in the process of trying to separate out the JSON parts into a more stand alone library, but that effort is still at least a few months out.

To see the full set of what you need you can look in the .travis files (<https://github.com/KayEss/json-schema/blob/master/.travis.yml> and <https://github.com/KayEss/json-schema/blob/master/.travis.CMakeLists.txt>) and see the script they do. If you reproduce that you should be able to get a working build and from there decide if you want these other dependencies for now, but you will absolutely need C++17.

**Comment by walterzhaoJR** [comment]
OK.THX
Let me have a try!
